### ISSUE TITLE
Error: TemplateDoesNotExist: googlecharts/googlecharts.html

### ISSUE THREAD

**Issue by kuzmak** [mvasilkov/django-google-charts#3]
I got the "TemplateDoesNotExist: googlecharts/googlecharts.html" error after installing django-google-charts with PIP:
pip -E /opt/site-env install git+https://github.com/mvasilkov/django-google-charts.git
(or simply pip -E django-google-charts).

Solution was to copy the googlecharts.html from git repository to /opt/site-env/lib/python2.7/site-packages/googlecharts/templates/googlecharts folder.

Stack trace:
[Tue Nov 15 17:41:37 2011] [error]     return render_to_response('../graph.html', {'values': time_series})
[Tue Nov 15 17:41:37 2011] [error]   File "/opt/production-env/lib/python2.7/site-packages/django/shortcuts/**init**.py", line 20, in render_to_response
[Tue Nov 15 17:41:37 2011] [error]     return HttpResponse(loader.render_to_string(_args, *_kwargs), **httpresponse_kwargs)
[Tue Nov 15 17:41:37 2011] [error]   File "/opt/production-env/lib/python2.7/site-packages/django/template/loader.py", line 183, in render_to_string
[Tue Nov 15 17:41:37 2011] [error]     return t.render(Context(dictionary))
[Tue Nov 15 17:41:37 2011] [error]   File "/opt/production-env/lib/python2.7/site-packages/django/template/base.py", line 123, in render
[Tue Nov 15 17:41:37 2011] [error]     return self._render(context)
[Tue Nov 15 17:41:37 2011] [error]   File "/opt/production-env/lib/python2.7/site-packages/django/template/base.py", line 117, in _render
[Tue Nov 15 17:41:37 2011] [error]     return self.nodelist.render(context)
[Tue Nov 15 17:41:37 2011] [error]   File "/opt/production-env/lib/python2.7/site-packages/django/template/base.py", line 744, in render
[Tue Nov 15 17:41:37 2011] [error]     bits.append(self.render_node(node, context))
[Tue Nov 15 17:41:37 2011] [error]   File "/opt/production-env/lib/python2.7/site-packages/django/template/base.py", line 757, in render_node
[Tue Nov 15 17:41:37 2011] [error]     return node.render(context)
[Tue Nov 15 17:41:37 2011] [error]   File "/opt/production-env/lib/python2.7/site-packages/googlecharts/templatetags/googlecharts.py", line 20, in render
[Tue Nov 15 17:41:37 2011] [error]     return self.render_template('googlecharts/googlecharts.html', googlecharts_js=js, api=_api)
[Tue Nov 15 17:41:37 2011] [error]   File "/opt/production-env/lib/python2.7/site-packages/googlecharts/templatetags/googlecharts.py", line 16, in render_template
[Tue Nov 15 17:41:37 2011] [error]     return render_to_string(template, kwargs)
[Tue Nov 15 17:41:37 2011] [error]   File "/opt/production-env/lib/python2.7/site-packages/django/template/loader.py", line 181, in render_to_string
[Tue Nov 15 17:41:37 2011] [error]     t = get_template(template_name)
[Tue Nov 15 17:41:37 2011] [error]   File "/opt/production-env/lib/python2.7/site-packages/django/template/loader.py", line 157, in get_template
[Tue Nov 15 17:41:37 2011] [error]     template, origin = find_template(template_name)
[Tue Nov 15 17:41:37 2011] [error]   File "/opt/production-env/lib/python2.7/site-packages/django/template/loader.py", line 138, in find_template
[Tue Nov 15 17:41:37 2011] [error]     raise TemplateDoesNotExist(name)
[Tue Nov 15 17:41:37 2011] [error] TemplateDoesNotExist: googlecharts/googlecharts.html

**Comment by mvasilkov** [comment]
Did you include `'googlecharts'` in your `INSTALLED_APPS`? Do you have `'django.template.loaders.app_directories.Loader'` in your `TEMPLATE_LOADERS`? It depends on these two, basically.

**Comment by kuzmak** [comment]
Yes, in my settings.py I have the following:

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.load_template_source',
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.load_template_source',
    'django.template.loaders.app_directories.Loader',

# 'django.template.loaders.eggs.load_template_source',

)

as well as:

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.databrowse',
    ...
    'compressor',
    'indexer',
    'paging',
    'sentry',
    'sentry.client',
    'debug_toolbar',
    'googlecharts',
)

If I create /opt/site-env/lib/python2.7/site-packages/googlecharts/templates/googlecharts folder and copy googlecharts.html from git repository into it, everything works great.

**Comment by mvasilkov** [comment]
Yup, sorry, my bad ._. `setup.py` doesn’t actually track those files. I’ll fix the package today.

**Comment by mvasilkov** [comment]
Should work now. Thank you for the bug report :)

**Comment by kuzmak** [comment]
Thank you! It works great now.
