### ISSUE TITLE
Put forloop.counter0 into graph argument list possible?

### ISSUE THREAD

**Issue by sfdye** [mvasilkov/django-google-charts#4]
Hi mvasilkov

Here is an issue I have put on stackoverflow, 

http://stackoverflow.com/questions/12930169/django-put-forloop-counter0-into-custom-tag-argument-list-possible

Please help.

Thank you very much.

**Comment by jdeprin** [comment]
In case anyone finds this on google, I had this issue and ended up adding the functionality in https://github.com/mvasilkov/django-google-charts/pull/13

```
{% for key,value in data.items %}
    ...
    {% graph key "data" "options" %}
    ...
{% endfor %}
```

```
{% for key,value in data.items %}
    <div id="{{ key }}"></div>
{% endfor %}
```
