### ISSUE TITLE
Can't be used from a checkout.

### ISSUE THREAD

**Issue by regebro** [mvasilkov/django-google-charts#6]
Since there is a settings.py in the root, this can end up in the python path and get picked up before the proper application settings.py. The demo app should instead be in a separate subdirectory.

**Comment by mvasilkov** [comment]
Sound strange since one usually defines `DJANGO_SETTINGS_MODULE`. And sure, you're right.

**Comment by mvasilkov** [comment]
You're welcome to push to the repo if you like.

**Comment by regebro** [comment]
Thanks! I'll push my changes tomorrow.
